// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr6Zqi5VmO-2GI3zBDnFk5Ku6hRASwbaI',
    appId: '1:229990261595:web:d9cb284151bad290d3b07e',
    messagingSenderId: '229990261595',
    projectId: 'budget-home-bayoumi',
    // Firebase's default *.firebaseapp.com auth domain. Google specially
    // handles this domain for sign-in across browsers (incl. Chrome on
    // Android), unlike a custom web.app domain which broke mobile Chrome.
    authDomain: 'budget-home-bayoumi.firebaseapp.com',
    storageBucket: 'budget-home-bayoumi.firebasestorage.app',
    measurementId: 'G-0RNZB7PVNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmkvJhsNmUvyxD9zepHGt79z7PbIrYP20',
    appId: '1:229990261595:android:7d04e99f1dbf3e45d3b07e',
    messagingSenderId: '229990261595',
    projectId: 'budget-home-bayoumi',
    storageBucket: 'budget-home-bayoumi.firebasestorage.app',
  );
}
